import argparse
import json
import os
import uuid
from decimal import Decimal
from pathlib import Path

from core.spm_api import SPMApiError, SPMClient


def _load_dotenv() -> None:
    env_path = Path(__file__).resolve().parent / ".env"
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def _require(value: str, flag: str, env_var: str) -> str:
    if not value:
        raise SystemExit(f"Missing {env_var}. Provide it via {flag} or env var {env_var}.")
    return value


def _build_client(args: argparse.Namespace) -> SPMClient:
    base_url = args.base_url or os.environ.get("SPM_API_BASE") or "https://ext.sportsmanager.app"
    public_key = args.public_key or os.environ.get("SPM_PUBLIC_KEY")
    secret_key = args.secret_key or os.environ.get("SPM_SECRET_KEY")

    public_key = _require(public_key or "", "--public-key", "SPM_PUBLIC_KEY")
    secret_key = _require(secret_key or "", "--secret-key", "SPM_SECRET_KEY")

    return SPMClient(base_url=base_url, public_key=public_key, secret_key=secret_key)


def _print_ok(balance: Decimal, txn_id: str) -> None:
    print(
        json.dumps(
            {
                "error": None,
                "data": {"balance": str(balance), "txnId": txn_id},
                "statusCode": 200,
            },
            indent=2,
        )
    )


def _print_err(e: SPMApiError) -> None:
    print(
        json.dumps(
            {
                "error": {"message": str(e), "errorCode": e.error_code},
                "data": None,
                "statusCode": e.status_code,
            },
            indent=2,
        )
    )


def main() -> None:
    _load_dotenv()

    parser = argparse.ArgumentParser(
        description="Demo client for external SPM API deposit/withdraw (direct external calls)."
    )
    parser.add_argument("--base-url", default=None, help="SPM API base URL (env: SPM_API_BASE)")
    parser.add_argument("--public-key", default=None, help="SPM public key (env: SPM_PUBLIC_KEY)")
    parser.add_argument("--secret-key", default=None, help="SPM secret key (env: SPM_SECRET_KEY)")

    sub = parser.add_subparsers(dest="command", required=True)

    for name in ("deposit", "withdraw"):
        p = sub.add_parser(name)
        p.add_argument("--amount", required=True, help="Amount (e.g. 100.00)")
        p.add_argument("--user-id", required=True, type=int, help="SPM userId")
        p.add_argument("--txn-id", default=None, help="txnId (optional, autogenerated if omitted)")
        p.add_argument("--remarks", default="", help="Optional remarks")

    args = parser.parse_args()

    client = _build_client(args)
    amount = Decimal(str(args.amount))
    txn_id = args.txn_id or str(uuid.uuid4())

    try:
        if args.command == "deposit":
            balance = client.deposit(
                amount=amount,
                user_id=args.user_id,
                txn_id=txn_id,
                remarks=args.remarks,
            )
            _print_ok(balance=balance, txn_id=txn_id)
            return

        if args.command == "withdraw":
            balance = client.withdraw(
                amount=amount,
                user_id=args.user_id,
                txn_id=txn_id,
                remarks=args.remarks,
            )
            _print_ok(balance=balance, txn_id=txn_id)
            return

        raise SystemExit(f"Unknown command: {args.command}")

    except SPMApiError as e:
        _print_err(e)


if __name__ == "__main__":
    main()
