# Generated by Django 5.1.15 on 2025-12-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
