# Generated by Django 5.1.15 on 2025-12-23 21:24

from django.db import migrations, models
from django.db.models import Case, DecimalField, F, Sum, Value, When


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_wallet_balance(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _backfill_wallet_balance(apps):
    Wallet = apps.get_model("core", "Wallet")
    Transaction = apps.get_model("core", "Transaction")

    signed_amount_expr = Case(
        When(type="withdraw", then=F("amount") * Value(-1)),
        default=F("amount"),
        output_field=DecimalField(max_digits=12, decimal_places=2),
    )
    qs = (
        Transaction.objects.filter(status="approved")
        .values("wallet_id")
        .annotate(total=Sum(signed_amount_expr))
    )
    totals = {row["wallet_id"]: row["total"] for row in qs}
    for w in Wallet.objects.all():
        Wallet.objects.filter(pk=w.pk).update(balance=totals.get(w.pk) or 0)
