# Generated by Django 5.1.15 on 2025-12-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_external_balance_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
