# Generated by Django 5.1.15 on 2025-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wallettransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='TMT', max_length=8),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _set_usd_to_tmt(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _set_usd_to_tmt(apps):
    Wallet = apps.get_model("core", "Wallet")
    Wallet.objects.filter(currency="USD").update(currency="TMT")
