# Generated by Django 5.1.15 on 2025-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.AlterModelOptions(
            name='wallettransfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Перевод кошелька', 'verbose_name_plural': 'Переводы кошельков'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Депозит'), ('withdraw', 'Вывод')], default='withdraw', max_length=16),
        ),
    ]
