# Generated by Django 5.1.15 on 2025-12-26 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_options_alter_wallet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_referral_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_sync_error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка синхронизации'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='Статус синхронизации'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_user_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID клиента'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_user_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Депозит'), ('withdraw', 'Вывод')], default='withdraw', max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet', verbose_name='Кошелёк'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='TMT', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='core.wallet', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.wallet', verbose_name='Кому'),
        ),
    ]
