# Generated by Django 5.1.15 on 2026-01-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransfer',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
